#include "props_up.h"
#include<iostream>
#include<stdlib.h>

prop_memo_table22 memo_table_enthalpy_up;
prop_memo_table22 memo_table_entropy_up;
prop_memo_table22 memo_table_gibbs_up;
prop_memo_table22 memo_table_helmholtz_up;
prop_memo_table22 memo_table_isochoric_heat_capacity_up;
prop_memo_table22 memo_table_isobaric_heat_capacity_up;
prop_memo_table22 memo_table_speed_of_sound_up;
prop_memo_table22 memo_table_isothermal_compressibility_up;
prop_memo_table22 memo_table_log_fugacity_coefficient_up;
prop_memo_table22 memo_table_specific_volume_up;
prop_memo_table22 memo_table_temperature_up;
prop_memo_table22 memo_table_vapor_fraction_up;
prop_memo_table22 memo_table_viscosity_up;
prop_memo_table22 memo_table_thermal_conductivity_up;
prop_memo_table22 memo_table_surface_tension_up;

prop_memo_table22 memo_table_internal_energy_liq_up;
prop_memo_table22 memo_table_enthalpy_liq_up;
prop_memo_table22 memo_table_entropy_liq_up;
prop_memo_table22 memo_table_gibbs_liq_up;
prop_memo_table22 memo_table_helmholtz_liq_up;
prop_memo_table22 memo_table_isochoric_heat_capacity_liq_up;
prop_memo_table22 memo_table_isobaric_heat_capacity_liq_up;
prop_memo_table22 memo_table_speed_of_sound_liq_up;
prop_memo_table22 memo_table_isothermal_compressibility_liq_up;
prop_memo_table22 memo_table_log_fugacity_coefficient_liq_up;
prop_memo_table22 memo_table_specific_volume_liq_up;
prop_memo_table22 memo_table_viscosity_liq_up;
prop_memo_table22 memo_table_thermal_conductivity_liq_up;
prop_memo_table22 memo_table_surface_tension_liq_up;

prop_memo_table22 memo_table_internal_energy_vap_up;
prop_memo_table22 memo_table_enthalpy_vap_up;
prop_memo_table22 memo_table_entropy_vap_up;
prop_memo_table22 memo_table_gibbs_vap_up;
prop_memo_table22 memo_table_helmholtz_vap_up;
prop_memo_table22 memo_table_isochoric_heat_capacity_vap_up;
prop_memo_table22 memo_table_isobaric_heat_capacity_vap_up;
prop_memo_table22 memo_table_speed_of_sound_vap_up;
prop_memo_table22 memo_table_isothermal_compressibility_vap_up;
prop_memo_table22 memo_table_log_fugacity_coefficient_vap_up;
prop_memo_table22 memo_table_specific_volume_vap_up;
prop_memo_table22 memo_table_viscosity_vap_up;
prop_memo_table22 memo_table_thermal_conductivity_vap_up;
prop_memo_table22 memo_table_surface_tension_vap_up;

//T
void temperature_up(uint comp, double u, double p, f22_struct *out){ 
    f22_struct tau_vec = memo2_tau_up(comp, u, p);
    out->f = cdata[comp].T_star/tau_vec.f;
    out->f_1 = -cdata[comp].T_star/tau_vec.f/tau_vec.f*tau_vec.f_1;
    out->f_2 = -cdata[comp].T_star/tau_vec.f/tau_vec.f*tau_vec.f_2;
    out->f_11 = 2*cdata[comp].T_star/tau_vec.f/tau_vec.f/tau_vec.f*tau_vec.f_1*tau_vec.f_1 - cdata[comp].T_star/tau_vec.f/tau_vec.f*tau_vec.f_11;
    out->f_12 = 2*cdata[comp].T_star/tau_vec.f/tau_vec.f/tau_vec.f*tau_vec.f_1*tau_vec.f_2 - cdata[comp].T_star/tau_vec.f/tau_vec.f*tau_vec.f_12;
    out->f_22 = 2*cdata[comp].T_star/tau_vec.f/tau_vec.f/tau_vec.f*tau_vec.f_2*tau_vec.f_2 - cdata[comp].T_star/tau_vec.f/tau_vec.f*tau_vec.f_22;
}
MEMO2_FUNCTION(memo2_temperature_up, temperature_up, memo_table_temperature_up)

//vapor_fraction
void vapor_fraction_up(uint comp, double u, double p, f22_struct *out){ 
    f22_struct vf_vec = memo2_vf_up(comp, u, p);
    out->f = vf_vec.f;
    out->f_1 = vf_vec.f_1;
    out->f_2 = vf_vec.f_2;
    out->f_11 = vf_vec.f_11;
    out->f_12 = vf_vec.f_12;
    out->f_22 = vf_vec.f_22;
}
MEMO2_FUNCTION(memo2_vapor_fraction_up, vapor_fraction_up, memo_table_vapor_fraction_up)

//u
PROP_UP_SINGLE_PHASE(internal_energy_vap_up, memo2_internal_energy, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(internal_energy_liq_up, memo2_internal_energy, memo2_delta_liquid)
MEMO2_FUNCTION(memo2_internal_energy_vap_up, internal_energy_vap_up, memo_table_internal_energy_vap_up)
MEMO2_FUNCTION(memo2_internal_energy_liq_up, internal_energy_liq_up, memo_table_internal_energy_liq_up)

//h
PROP_UP_SINGLE_PHASE(enthalpy_vap_up, memo2_enthalpy, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(enthalpy_liq_up, memo2_enthalpy, memo2_delta_liquid)
PROP_UP_GENERAL(enthalpy_up, enthalpy_liq_up, enthalpy_vap_up)
MEMO2_FUNCTION(memo2_enthalpy_up, enthalpy_up, memo_table_enthalpy_up)
MEMO2_FUNCTION(memo2_enthalpy_vap_up, enthalpy_vap_up, memo_table_enthalpy_vap_up)
MEMO2_FUNCTION(memo2_enthalpy_liq_up, enthalpy_liq_up, memo_table_enthalpy_liq_up)

//s
PROP_UP_SINGLE_PHASE(entropy_vap_up, memo2_entropy, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(entropy_liq_up, memo2_entropy, memo2_delta_liquid)
PROP_UP_GENERAL(entropy_up, entropy_liq_up, entropy_vap_up)
MEMO2_FUNCTION(memo2_entropy_up, entropy_up, memo_table_entropy_up)
MEMO2_FUNCTION(memo2_entropy_vap_up, entropy_vap_up, memo_table_entropy_vap_up)
MEMO2_FUNCTION(memo2_entropy_liq_up, entropy_liq_up, memo_table_entropy_liq_up)

//g
PROP_UP_SINGLE_PHASE(gibbs_vap_up, memo2_gibbs, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(gibbs_liq_up, memo2_gibbs, memo2_delta_liquid)
PROP_UP_GENERAL(gibbs_up, gibbs_liq_up, gibbs_vap_up)
MEMO2_FUNCTION(memo2_gibbs_up, gibbs_up, memo_table_gibbs_up)
MEMO2_FUNCTION(memo2_gibbs_vap_up, gibbs_vap_up, memo_table_gibbs_vap_up)
MEMO2_FUNCTION(memo2_gibbs_liq_up, gibbs_liq_up, memo_table_gibbs_liq_up)

//f
PROP_UP_SINGLE_PHASE(helmholtz_vap_up, memo2_helmholtz, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(helmholtz_liq_up, memo2_helmholtz, memo2_delta_liquid)
PROP_UP_GENERAL(helmholtz_up, helmholtz_liq_up, helmholtz_vap_up)
MEMO2_FUNCTION(memo2_helmholtz_up, helmholtz_up, memo_table_helmholtz_up)
MEMO2_FUNCTION(memo2_helmholtz_vap_up, helmholtz_vap_up, memo_table_helmholtz_vap_up)
MEMO2_FUNCTION(memo2_helmholtz_liq_up, helmholtz_liq_up, memo_table_helmholtz_liq_up)

//cv
PROP_UP_SINGLE_PHASE(isochoric_heat_capacity_vap_up, memo2_isochoric_heat_capacity, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(isochoric_heat_capacity_liq_up, memo2_isochoric_heat_capacity, memo2_delta_liquid)
PROP_UP_GENERAL(isochoric_heat_capacity_up, isochoric_heat_capacity_liq_up, isochoric_heat_capacity_vap_up)
MEMO2_FUNCTION(memo2_isochoric_heat_capacity_up, isochoric_heat_capacity_up, memo_table_isochoric_heat_capacity_up)
MEMO2_FUNCTION(memo2_isochoric_heat_capacity_vap_up, isochoric_heat_capacity_vap_up, memo_table_isochoric_heat_capacity_vap_up)
MEMO2_FUNCTION(memo2_isochoric_heat_capacity_liq_up, isochoric_heat_capacity_liq_up, memo_table_isochoric_heat_capacity_liq_up)

//cp
PROP_UP_SINGLE_PHASE(isobaric_heat_capacity_vap_up, memo2_isobaric_heat_capacity, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(isobaric_heat_capacity_liq_up, memo2_isobaric_heat_capacity, memo2_delta_liquid)
PROP_UP_GENERAL(isobaric_heat_capacity_up, isobaric_heat_capacity_liq_up, isobaric_heat_capacity_vap_up)
MEMO2_FUNCTION(memo2_isobaric_heat_capacity_up, isobaric_heat_capacity_up, memo_table_isobaric_heat_capacity_up)
MEMO2_FUNCTION(memo2_isobaric_heat_capacity_vap_up, isobaric_heat_capacity_vap_up, memo_table_isobaric_heat_capacity_vap_up)
MEMO2_FUNCTION(memo2_isobaric_heat_capacity_liq_up, isobaric_heat_capacity_liq_up, memo_table_isobaric_heat_capacity_liq_up)

//w (doesn't really mean much in the two phase region, so use with care)
PROP_UP_SINGLE_PHASE(speed_of_sound_vap_up, memo2_speed_of_sound, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(speed_of_sound_liq_up, memo2_speed_of_sound, memo2_delta_liquid)
PROP_UP_GENERAL(speed_of_sound_up, speed_of_sound_liq_up, speed_of_sound_vap_up)
MEMO2_FUNCTION(memo2_speed_of_sound_up, speed_of_sound_up, memo_table_speed_of_sound_up)
MEMO2_FUNCTION(memo2_speed_of_sound_vap_up, speed_of_sound_vap_up, memo_table_speed_of_sound_vap_up)
MEMO2_FUNCTION(memo2_speed_of_sound_liq_up, speed_of_sound_liq_up, memo_table_speed_of_sound_liq_up)

//isothermal compressability (doesn't really mean much in the two phase region, so use with care)
PROP_UP_SINGLE_PHASE(isothermal_compressibility_vap_up, memo2_isothermal_compressibility, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(isothermal_compressibility_liq_up, memo2_isothermal_compressibility, memo2_delta_liquid)
PROP_UP_GENERAL(isothermal_compressibility_up, isothermal_compressibility_liq_up, isothermal_compressibility_vap_up)
MEMO2_FUNCTION(memo2_isothermal_compressibility_up, isothermal_compressibility_up, memo_table_isothermal_compressibility_up)
MEMO2_FUNCTION(memo2_isothermal_compressibility_vap_up, isothermal_compressibility_vap_up, memo_table_isothermal_compressibility_vap_up)
MEMO2_FUNCTION(memo2_isothermal_compressibility_liq_up, isothermal_compressibility_liq_up, memo_table_isothermal_compressibility_liq_up)

//log fugacity coefficient
PROP_UP_SINGLE_PHASE(log_fugacity_coefficient_vap_up, memo2_log_fugacity_coefficient, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(log_fugacity_coefficient_liq_up, memo2_log_fugacity_coefficient, memo2_delta_liquid)
PROP_UP_GENERAL(log_fugacity_coefficient_up, log_fugacity_coefficient_liq_up, log_fugacity_coefficient_vap_up)
MEMO2_FUNCTION(memo2_log_fugacity_coefficient_up, log_fugacity_coefficient_up, memo_table_log_fugacity_coefficient_up)
MEMO2_FUNCTION(memo2_log_fugacity_coefficient_vap_up, log_fugacity_coefficient_vap_up, memo_table_log_fugacity_coefficient_vap_up)
MEMO2_FUNCTION(memo2_log_fugacity_coefficient_liq_up, log_fugacity_coefficient_liq_up, memo_table_log_fugacity_coefficient_liq_up)

//v
PROP_UP_SINGLE_PHASE(specific_volume_vap_up, memo2_specific_volume, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(specific_volume_liq_up, memo2_specific_volume, memo2_delta_liquid)
PROP_UP_GENERAL(specific_volume_up, specific_volume_liq_up, specific_volume_vap_up)
MEMO2_FUNCTION(memo2_specific_volume_up, specific_volume_up, memo_table_specific_volume_up)
MEMO2_FUNCTION(memo2_specific_volume_vap_up, specific_volume_vap_up, memo_table_specific_volume_vap_up)
MEMO2_FUNCTION(memo2_specific_volume_liq_up, specific_volume_liq_up, memo_table_specific_volume_liq_up)

//viscosity
PROP_UP_SINGLE_PHASE(viscosity_vap_up, memo2_viscosity, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(viscosity_liq_up, memo2_viscosity, memo2_delta_liquid)
PROP_UP_GENERAL(viscosity_up, viscosity_liq_up, viscosity_vap_up)
MEMO2_FUNCTION(memo2_viscosity_up, viscosity_up, memo_table_viscosity_up)
MEMO2_FUNCTION(memo2_viscosity_vap_up, viscosity_vap_up, memo_table_viscosity_vap_up)
MEMO2_FUNCTION(memo2_viscosity_liq_up, viscosity_liq_up, memo_table_viscosity_liq_up)

//thermal conductivity
PROP_UP_SINGLE_PHASE(thermal_conductivity_vap_up, memo2_thermal_conductivity, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(thermal_conductivity_liq_up, memo2_thermal_conductivity, memo2_delta_liquid)
PROP_UP_GENERAL(thermal_conductivity_up, thermal_conductivity_liq_up, thermal_conductivity_vap_up)
MEMO2_FUNCTION(memo2_thermal_conductivity_up, thermal_conductivity_up, memo_table_thermal_conductivity_up)
MEMO2_FUNCTION(memo2_thermal_conductivity_vap_up, thermal_conductivity_vap_up, memo_table_thermal_conductivity_vap_up)
MEMO2_FUNCTION(memo2_thermal_conductivity_liq_up, thermal_conductivity_liq_up, memo_table_thermal_conductivity_liq_up)

//surface tension
PROP_UP_SINGLE_PHASE(surface_tension_vap_up, memo2_surface_tension, memo2_delta_vapor)
PROP_UP_SINGLE_PHASE(surface_tension_liq_up, memo2_surface_tension, memo2_delta_liquid)
PROP_UP_GENERAL(surface_tension_up, surface_tension_liq_up, surface_tension_vap_up)
MEMO2_FUNCTION(memo2_surface_tension_up, surface_tension_up, memo_table_surface_tension_up)
MEMO2_FUNCTION(memo2_surface_tension_vap_up, surface_tension_vap_up, memo_table_surface_tension_vap_up)
MEMO2_FUNCTION(memo2_surface_tension_liq_up, surface_tension_liq_up, memo_table_surface_tension_liq_up)